# Generated by Django 4.2.29 on 2026-03-25 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(default='Araripina', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(default='PE', max_length=2, verbose_name='Estado')),
                ('especialidade', models.CharField(choices=[('natacao_infantil', 'Natação Infantil'), ('bebe_conforto', 'Bebê Conforto'), ('auto_salvamento', 'Auto Salvamento'), ('hidroginastica', 'Hidroginástica'), ('geral', 'Geral')], default='natacao_infantil', max_length=30, verbose_name='Especialidade')),
                ('formacao', models.CharField(blank=True, max_length=200, verbose_name='Formação')),
                ('registro_cref', models.CharField(blank=True, max_length=30, verbose_name='CREF')),
                ('anos_experiencia', models.PositiveIntegerField(default=0, verbose_name='Anos de Experiência')),
                ('tipo_contrato', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('autonomo', 'Autônomo'), ('voluntario', 'Voluntário')], default='clt', max_length=20, verbose_name='Tipo de Contrato')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Salário/Valor')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('afastado', 'Afastado'), ('desligado', 'Desligado')], default='ativo', max_length=20, verbose_name='Status')),
                ('data_admissao', models.DateField(default=datetime.date.today, verbose_name='Data de Admissão')),
                ('data_desligamento', models.DateField(blank=True, null=True, verbose_name='Data de Desligamento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='professores/fotos/', verbose_name='Foto')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia/Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Professor/Instrutor',
                'verbose_name_plural': 'Professores/Instrutores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Início')),
                ('hora_fim', models.TimeField(verbose_name='Fim')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='professores.professor', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Horário de Disponibilidade',
                'verbose_name_plural': 'Horários de Disponibilidade',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
