# Generated by Django 4.2.29 on 2026-03-25 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('telefone_emergencia', models.CharField(blank=True, max_length=20, verbose_name='Tel. Emergência')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('parentesco', models.CharField(choices=[('mae', 'Mãe'), ('pai', 'Pai'), ('avo', 'Avó/Avô'), ('tio', 'Tio/Tia'), ('responsavel', 'Responsável Legal'), ('outro', 'Outro')], default='mae', max_length=30, verbose_name='Parentesco')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(default='Araripina', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(default='PE', max_length=2, verbose_name='Estado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('faixa_etaria', models.CharField(choices=[('bebe', 'Bebê (0-2 anos)'), ('toddler', 'Toddler (2-4 anos)'), ('kids', 'Kids (4-6 anos)')], max_length=20, verbose_name='Faixa Etária')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('trancado', 'Trancado')], default='ativo', max_length=20, verbose_name='Status')),
                ('tipo_sanguineo', models.CharField(blank=True, max_length=5, verbose_name='Tipo Sanguíneo')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias')),
                ('medicamentos', models.TextField(blank=True, verbose_name='Medicamentos em uso')),
                ('condicoes_especiais', models.TextField(blank=True, verbose_name='Condições Especiais')),
                ('plano_saude', models.CharField(blank=True, max_length=100, verbose_name='Plano de Saúde')),
                ('autorizacao_foto', models.BooleanField(default=False, verbose_name='Autoriza uso de foto')),
                ('autorizacao_saida', models.BooleanField(default=False, verbose_name='Autoriza saída sozinho')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/fotos/', verbose_name='Foto')),
                ('documento', models.FileField(blank=True, null=True, upload_to='alunos/docs/', verbose_name='Documento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_matricula', models.DateField(default=datetime.date.today, verbose_name='Data de Matrícula')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos_principal', to='alunos.responsavel', verbose_name='Responsável Principal')),
                ('responsavel_secundario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_secundario', to='alunos.responsavel', verbose_name='Responsável Secundário')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
    ]
