# Generated by Django 4.2.29 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='status',
            field=models.CharField(choices=[('pendente', 'Em dia'), ('paga', 'Paga'), ('parcial', 'Parcialmente Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]