# Generated by Django 4.2.29 on 2026-03-25 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0001_initial'),
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Turma')),
                ('faixa_etaria', models.CharField(choices=[('bebe', 'Bebê (0-2 anos)'), ('toddler', 'Toddler (2-4 anos)'), ('kids', 'Kids (4-6 anos)'), ('mista', 'Turma Mista')], max_length=20, verbose_name='Faixa Etária')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado')], verbose_name='Dia da Semana')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Fim')),
                ('capacidade', models.PositiveIntegerField(default=10, verbose_name='Capacidade Máxima')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('encerrada', 'Encerrada')], default='ativa', max_length=20, verbose_name='Status')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('professor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas_responsavel', to='professores.professor', verbose_name='Professor Responsável')),
                ('professores_auxiliares', models.ManyToManyField(blank=True, related_name='turmas_auxiliar', to='professores.professor', verbose_name='Professores Auxiliares')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['dia_semana', 'horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor da Mensalidade (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='alunos.aluno', verbose_name='Aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='turmas.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ativa')), fields=('aluno', 'turma'), name='unique_matricula_ativa_por_turma'),
        ),
    ]
