# Generated by Django 4.2.29 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='frequencia_semanal',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 vez por semana'), (2, '2 vezes por semana')], default=1, verbose_name='Frequência Semanal'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='plano',
            field=models.CharField(choices=[('semestral', 'Semestral'), ('anual', 'Anual')], default='semestral', max_length=20, verbose_name='Plano'),
        ),
    ]