# Generated by Django 4.2.29 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_matricula_plano_frequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='cobranca_personalizada',
            field=models.BooleanField(default=False, verbose_name='Cobrança Personalizada'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='valor_personalizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Personalizado (R$)'),
        ),
    ]