# Generated by Django 4.2.29 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_matricula_cobranca_personalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='dia_vencimento',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Dia de Vencimento'),
        ),
    ]